package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.concurrent.TimeUnit;

public class ContactCreationTest {
  private static WebDriver driver;

  @BeforeMethod
  public void setUp() throws Exception {
    driver = new FirefoxDriver(new FirefoxOptions().setLegacy(true).setBinary("/home/elmirabaltinova/firefox-sdk/bin/firefox"));;
    driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    driver.get("http://localhost/addressbook/index.php");
    login("admin", "secret");
  }

  private void login(String username, String password) {
    driver.findElement(By.name("user")).click();
    driver.findElement(By.name("user")).sendKeys(username);
    driver.findElement(By.name("pass")).click();
    driver.findElement(By.name("pass")).sendKeys(password);
    driver.findElement(By.cssSelector("input:nth-child(7)")).click();
  }

  @Test
  public void contactCreation() {
    initContactCreation();
    fillContactForm("Bekki", "Howard", "332211", "bekki@howard.com");
    submitContactCreation();
  }

  private void submitContactCreation() {
    driver.findElement(By.cssSelector("input:nth-child(87)")).click();
  }

  private void fillContactForm(String firstname, String lastname, String number_home, String email) {
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys(firstname);
    driver.findElement(By.name("lastname")).click();
    driver.findElement(By.name("lastname")).sendKeys(lastname);
    driver.findElement(By.name("home")).click();
    driver.findElement(By.name("home")).sendKeys(number_home);
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys(email);
  }

  private void initContactCreation() {
    driver.findElement(By.linkText("add new")).click();
  }

  @AfterMethod
  public void tearDown() {
    driver.quit();
  }

  public static boolean isAlertPresent(FirefoxDriver Driver) {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

}
