package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.testng.annotations.Test;

public class ContactCreationTest extends TestBase {

    @Test
    public void testContactCreation() {
        app.initContactCreation();
        app.fillContactForm(new ContactData("Bekki", "Howard", "332211", "bekki@howard.com"));
        app.submitContactCreation();
    }


}
